services:
  comfyui-latest:
    image: comfyui:latest
    environment:
      - TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
    volumes:
      - ${HOME}/.comfyui/input:/app/input
      - ${HOME}/.comfyui/output:/app/output
      - ${HOME}/.comfyui/models:/app/models
      - ${HOME}/.comfyui/user:/app/user
      - ${HOME}/.comfyui/custom_nodes:/app/custom_nodes
    ports:
      - "8188:8188"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    ipc: host
    shm_size: 8G
    command: ["python3", "/app/main.py", "--listen", "0.0.0.0", "--use-pytorch-cross-attention"]
